### ISSUE TITLE
TR: harmonize functions to plot toy examples

### ISSUE THREAD

**Issue by afcastrot** [timriffe/Spells#14]
Document current functions (draw_sequencesX) to make it easier to plot toy examples, i.e., the examples we use to illustrate concepts with 10 sequences. Keep in mind these functions should be useful for future presentations and not only this paper

**Comment by timriffe** [comment]
I added a new function to the package, so you can reinstall it. It's called `draw_sequence()`, and it handles trajectory coloring, it has an `x` arg to take an `align()` operation in situ, and a `labels` arg to handle clock labelling in situ. There is an example showing this, and example data for ten working trajectories has also been added to the package (`X`, sorry non-descriptive name)
